### ISSUE TITLE
pages having different layouts

### ISSUE THREAD

**Issue by charlesrocket** [andrewbanchich/dimension-jekyll-theme#3]
i noticed that `elements` page reads markdown properly, while other pages failing to read markdown properly. i guess thats missing `layout` tag?

**Comment by andrewbanchich** [comment]
I'm not seeing this on the GitHub Pages demo. Do you have an example I can take a look at?

**Comment by charlesrocket** [comment]
@andrewbanchich i fixed most of it on my repo, but i guess this is because the absence of the proper layouts system? you can see here https://github.com/AXErunners/axerunners.github.io that core page has regular markdown while other pages don't

**Comment by andrewbanchich** [comment]
I'm not sure, but I don't think that's it. I only added the `layout` front matter setting to `index.md` since this is a single page template, and the text/markdown content is all I need for the different sections. Have you tried removing all the HTML from one and using only markdown?

**Comment by charlesrocket** [comment]
i had markdown-only pages before i was migrating the website, and had to rewrite since markdown was rendered properly only on one page

**Comment by andrewbanchich** [comment]
It looks like the issue is that I'm looping through all pages that are added for the convenience of it being able to dynamically add new pages to the menu. The downside to this is that in the loop, the page content is stored on the page object as `page.content` instead of the normal `content`. `content` is parsed by Jekyll to render Markdown, but `page.content` is not.

Unfortunately, I think that fixing this would require a larger update to the theme. Maybe I'll add that in the future, but I don't have a ton of time at the moment.<sup>pull requests welcome!</sup>
